### ISSUE TITLE
Wrong position indices in json output

### ISSUE THREAD

**Issue by anne17** [TALP-UPC/FreeLing#102]
The position indices in the json output in the following example seem wrong. This analysis was done using FreeLing 4.1 with the English standard config file. According to the json output the first token starts at position 0 and ends at 2 which corresponds to the string `Th`, while the second token starts at 3 and ends at 6, giving the string `t's`. This looks like an error.

Call: `analyze --output json -f en.cfg`
Input: `That's okay.`
(Shortened) output:
```{
    "sentences": [
        {
            "id": "1",
            "tokens": [
                {
                    "id": "t1.1",
                    "begin": "0",
                    "end": "2",
                    "form": "That",
                    "lemma": "that"
                },
                {
                    "id": "t1.2",
                    "begin": "3",
                    "end": "6",
                    "form": "'s",
                    "lemma": "be"
                },
                {
                    "id": "t1.3",
                    "begin": "7",
                    "end": "11",
                    "form": "okay",
                    "lemma": "okay"
                },
                {
                    "id": "t1.4",
                    "begin": "11",
                    "end": "12",
                    "form": ".",
                    "lemma": "."
                }
            ]
        }
    ]
}

**Comment by lluisp** [comment]
Thanks for pointint this out, I'll have a look

**Comment by anne17** [comment]
Sounds good, thanks! Do you have any estimate on when there will be a new release? :)

**Comment by lluisp** [comment]
You can get it right away from the master branch.
With some luck, there will be a new release this summer, although it is not sure it is available for Windows or Mac yet.

**Comment by anne17** [comment]
Thanks! We're looking forward to your next release! I guess this issue should be considered fixed, so let's close it.
