### ISSUE TITLE
Zlib

### ISSUE THREAD

**Issue by ambs** [TALP-UPC/FreeLing#11]
Hi, again.

From other issue thread:

> 
> i found it at http://zlib.net/fossils/
> It seems the change happened between 1.2.5.1 and 1.2.5.2
> So the code should be
> 
> #if ZLIB_VERNUM < 0x1252
> #define gzFile gzFile*
> #endif
> 
> it's already fixed in master
> 

In fact, my Mac has 1.2.5.0 and it doesn't work with this `define`. Changing it to 0x1250, for example, it starts working. Also, I can't see anybody changing such a thing in a patch version (1.2.5.1 to 1.2.5.2).

So, probably better to consider 0x1250 to be OK, and just do the define for versions below it. Meanwhile, if somebody with lower versions complain, we can always adjust.

Thanks

**Comment by lluisp** [comment]
The problem seems more related to the fact that the #if ZLIB_VERNUM < 0xNNNN  is not  returning true when the version is less than 0xNNNN, but when it is equal...

**Comment by ambs** [comment]
Sorry, I did not understand you answer. Of course that if you change it to 0x1250, it will not return true for version 1.2.5.0 (that I was expecting :-))

**Comment by lluisp** [comment]
I meant that I checked the code for all versions, and the change seemed to have happened in 1.2.5.2... but you're right that it is a weird thing to do.
Ok, if it works for you with 1.2.5.0, let's put it that way and see what happens.

**Comment by ambs** [comment]
Thanks :)

**Comment by lluisp** [comment]
pushed

**Comment by ambs** [comment]
other than that, compiled and installed in MacOS like a charm (was testing, given your changes)
