### ISSUE TITLE
Wrong URL to manual in latest release?

### ISSUE THREAD

**Issue by anne17** [TALP-UPC/FreeLing#110]
This URL (on the [release page](https://github.com/TALP-UPC/FreeLing/releases/tag/4.2)) https://talp-upc.gitbooks.io/freeling-4-1-user-manual/content/installation.html gives me a 404.

**Comment by lluisp** [comment]
Fixed. thanks!

(just FYI  : posting issues in the forum in FL webpage usally gets faster response)

**Comment by anne17** [comment]
Just for the record, is this the correct forum: http://nlp.lsi.upc.edu/freeling/forum ?

**Comment by lluisp** [comment]
yes, that's it
