### ISSUE TITLE
Semgraph Malformed JSON Output

### ISSUE THREAD

**Issue by rmarrugat** [TALP-UPC/FreeLing#113]
### 🌍 Environment

 - Your operating system and version: Ubuntu 18.04
 - Your FreeLing version: FreeLing 4.1

### :memo: Bug Description

Given a FreeLing instance initialized with Mode=Server, Output Level=Semgraph and Output=JSON, at the time of [generating the JSON Semgraph](https://github.com/TALP-UPC/FreeLing/blob/master/src/libfreeling/output/output_json.cc#L578), a comma (`','`) is added for each paragraph of the document. In case the paragraph [does not contain any sentence](https://github.com/TALP-UPC/FreeLing/blob/master/src/libfreeling/output/output_json.cc#L137), no paragraph JSON object is added to the semgraph report, which implies that the aformentioned added comma malforms the JSON semgraph report.

**Example**:

Given a document with 3 paragraphs where the 2nd one has no sentences, this would be the resulting output:

```JSON
{ "paragraphs" : [
   { "sentences" : [
      { "id":"1"}
     ]
    }
,
,
   { "sentences" : [
      { "id":"2"}
     ]
   }
]}
```

The comma (`','`) situated between the two sentences malforms the JSON.

### 💥 Reproducing

- FreeLing Server initialization command: `freeling/bin/analyze -f es.cfg --outlv semgraph --output json --nortk --flush --server --sense ukb --nec --numb --date --quant`

**Comment by lluisp** [comment]
Fixed in latest gitihub master branch
