### ISSUE TITLE
Cannot install on linux (Mint 20 = Ubuntu focal)

### ISSUE THREAD

**Issue by zhum** [TALP-UPC/FreeLing#119]
Try to compile and install. `make` finished without errors, but `make install` fails:

```
...
Install the project...
-- Install configuration: ""
-- Up-to-date: /opt/freeling/share/freeling
...
-- -- Creating ca/balear dictionary...
file "/home/serg/FreeLing-4.2/data/ca/balear/dictionary/header" not found
CMake Error at cmake_install.cmake:58 (message):
  multiword fusion failed with error: 255


make: *** [Makefile:86: install] Error 1
```

**Comment by lluisp** [comment]
Probably you did not download all language data packages, and there is a bug in the installer that tries to install them all anyway.

Workarounds: 
option 1) download all language data packages and try again.  You can safeliy remove unwanted language from /opt/freeling/share/freeling after installation

option 2) Install latest master version, where the installer is fixed and will try to install only present languages.

**Comment by zhum** [comment]
Yes, it worked! Probably, it is necessary to include these pre-requisites into README.linux (and windows/macos).
