### ISSUE TITLE
English text "Monday"

### ISSUE THREAD

**Issue by hamzahqt** [TALP-UPC/FreeLing#12]
Hi
i tried the demo in the link below
http://nlp.lsi.upc.edu/freeling/demo/demo.php
and when you put in 
Write your sentences
Monday 

and change the language to english
the result will be

Monday
[L:??/??/??:??.??:??]
W
1

**Comment by arademaker** [comment]
This is the expected output, it is saying that Monday was recognized as date (POS tag W).

**Comment by lluisp** [comment]
I added a description of the lemma for dates in the documentation 
https://talp-upc.gitbooks.io/freeling-user-manual/content/modules/dates.html
