### ISSUE TITLE
installation on Linux

### ISSUE THREAD

**Issue by arademaker** [TALP-UPC/FreeLing#20]
```
# autoreconf --install
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
Makefile.am: error: required file './NEWS' not found
Makefile.am: error: required file './ChangeLog' not found
autoreconf: automake failed with exit status: 1
```

New error ?

**Comment by bryant1410** [comment]
I think this is related to #19. These files have been deleted from the codebase. I don't understand why they are asked for in your Makefile.

**Comment by arademaker** [comment]
I bypassed this creating the two empty files:

```
$ touch NEWS
$ touch ChangeLog
```

**Comment by lluisp** [comment]
I added them back to the repo.   
It seems automake won't work unless they are present
