### ISSUE TITLE
add references about nerc/data files in the manual

### ISSUE THREAD

**Issue by arademaker** [TALP-UPC/FreeLing#21]
In the manual, I cloud not find any reference about how to update/improve the files in LANG/nerc/data ! For example, what is the diference between gazLOC-c.dat and gazLOC-p.dat ?

**Comment by lluisp** [comment]
Can you add issues about the manual in the manual gitbook, please?

**Comment by arademaker** [comment]
Not sure how to add issues in the manual, I added a discussion

https://www.gitbook.com/book/talp-upc/freeling-user-manual/discussions
