### ISSUE TITLE
installation errors with .deb

### ISSUE THREAD

**Issue by hfoffani** [TALP-UPC/FreeLing#27]
Hi,
I was trying the new .deb binary distribution and found some problems. I'm referring specifically to the `trusty-amd64.deb` under Debian 8.4 jessie 64.

After installation the `/usr/bin/analyzer` binary tries to load libboost-*.so version 1.54 libraries whereas the  current versions under Debian for libboost are the 1.55.0 ones.

I tried to install the 1.54 ones but apparently the aren't available (`apt-get` couldn't find them).

**Comment by lluisp** [comment]
uups, you're right... 
I will create packages for jessie and upload them tomorrow.

**Comment by lluisp** [comment]
Done.  You can download packages for jessie now.

**Comment by hfoffani** [comment]
Solved.
Thanks.
