### ISSUE TITLE
Freeling 4.0 in ubuntu 14.04 from deb package. Libboost problems.

### ISSUE THREAD

**Issue by jbonanat** [TALP-UPC/FreeLing#30]
Hello,

I'm trying to install freeling from "freeling-4.0-trusty-amd64.deb" package in Ubuntu 14.04. The problem is that this package requires libboost 1.55. But to execute analyze I need libboost 1.54. I solved this problem installing the deb package with libboost 1.55 and after freeling is installed I replaced libboost1.55 with libboost1.54.

Regards,
Jairo.

**Comment by lluisp** [comment]
yes, you are right, there is  a mismatch between the dependencies declared by the package and the actual dependencies of the binary.
Installing 1.54 should solve the problem (you can either keep 1.55 or not, as you will).

Alternatively, you can install freeling .deb with dpkg -i --force-depends, which will ignore the dependencies declared by the package and install FreeLing anyway.  If you have 1.54 installed (it is the default in 14.04, I think) you should be ok.

**Comment by bryant1410** [comment]
Is this solved?

**Comment by lluisp** [comment]
I understand the solution I proposed above is working.   Is it not?

**Comment by bryant1410** [comment]
Yeah, but couldn't the freeling deb package depend on libboost 1.54, so this workaround is avoided?

**Comment by lluisp** [comment]
It's not avoided. It'll be addressed at some moment, time allowing

**Comment by lluisp** [comment]
Dependencies declared by trusty packages have been fixed to boost 1.54

**Comment by bryant1410** [comment]
good to know, thanks!
