### ISSUE TITLE
method found_in_dict()

### ISSUE THREAD

**Issue by arademaker** [TALP-UPC/FreeLing#33]
http://nlp.lsi.upc.edu/freeling/doc/refman/classfreeling_1_1word.html#a90762dc4d7b73792f5e7c4091217d7e8

The method returned False when the word is found after an afixos rule was used:

```
financeiramente financeiro RG False
```

How can we know if a word was really guessed vs. transformed with afixos rules?

**Comment by lluisp** [comment]
That was a bit unclear and messy, so I changed it.
Now (in trunk version), class word has no longer a method found_in_dict

Instead, it now has the methods:
```
 void set_analyzed_by(unsigned);
bool is_analyzed_by(unsigned) const;
unsigned get_analyzed_by() const;
```

the 'unsigned' parameter is a bitmask that will tell you which modules analyzed that word:
You can compare the mask against any combination of:
```
word::USERMAP
word::NUMBERS
word::PUNCTUATION
word::DATES
word::DICTIONARY
word::AFFIXES
word::COMPOUNDS
word::MULTIWORDS
word::NER
word::QUANTITIES
word::PROBABILITIES
word::GUESSER
```

**Comment by arademaker** [comment]
@lluisp perfect! By /trunk/ you probably mean the branch /master/, right? ;-)

**Comment by arademaker** [comment]
It looks like the SWIG API wasn't updated yet:

```
# python3 process.py
Traceback (most recent call last):
  File "process.py", line 100, in <module>
    w.get_analyzed_by()
  File "/usr/local/lib/python3.4/dist-packages/freeling.py", line 1644, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, word, name)
  File "/usr/local/lib/python3.4/dist-packages/freeling.py", line 57, in _swig_getattr
    raise AttributeError(name)
AttributeError: get_analyzed_by
```

**Comment by lluisp** [comment]
I fixed it, try it now.

**Comment by arademaker** [comment]
Perfect. It worked! Now I have just to figure out the details about how to deal with the bitmask in Python! Not a big deal! Thanks.

**Comment by lluisp** [comment]
yes, of course   ;-)

El 26/10/16 a les 21:24, Alexandre Rademaker ha escrit:

**Comment by lluisp** [comment]
No, it was not.... feel free  ;-)

El 26/10/16 a les 22:27, Alexandre Rademaker ha escrit:

**Comment by arademaker** [comment]
@lluisp using the `bin()` function from Python to get a string representation of the bitmask I got, for example, `0b10000010010`. I am assuming the prefix `0b` is not informative and I should consider the 11 positions after it, am I right? But your list above has 12 lines. What am I missing?

**Comment by lluisp** [comment]
In an "int" there are 16 bits, so if the list has 12, there are still some bits unused.
You can check the C++ code (line 164 of
https://github.com/TALP-UPC/FreeLing/blob/master/src/include/freeling/morfo/language.h )
to find out which bits are which modules.
