### ISSUE TITLE
Compilation problems with GNU Make 4.1

### ISSUE THREAD

**Issue by beeva-hectoraguado** [TALP-UPC/FreeLing#39]
Hi,

I just do a change in the code because I had a problem compiling Freeling product with GNU Make 4.1 in an Alpine distribution, I have find this problem when I try to dockerizing the application. The problem was with some bools that were in Uppercase, and the compiler only accepts in lowercase, for this reason I just changed the code and I send you a pull request with the changes.

The changes are in this files:
- src/libfreeling/summarizer/relation.cc
- src/libfreeling/summarizer/summarizer.cc

Thanks and regards.

**Comment by lluisp** [comment]
pulled, thanks!
