### ISSUE TITLE
El API de python no compila

### ISSUE THREAD

**Issue by lanzalibre** [TALP-UPC/FreeLing#41]
Estimado Sr. Lladró:

El API de python no parece compilar. Obtengo el mismo error 

"Operator = ignored, Operator + ignored"

tanto siguiendo los pasos indicados en su manual como compilando el Dockerfile de Hernán Foffani (https://github.com/hfoffani/docker-freeling) ó Daniel Barragán (https://github.com/d4n13lbc/docker-freeling), por lo que no creo que sea un error siguiendo las instrucciones.

Gracias

**Comment by lluisp** [comment]
The python API was updated recently.  Please get the latest version from github

Also, SWIG produces some warnings about ignoring operators when creating the API, but that does not mean it is not built. They are just warnings.
