### ISSUE TITLE
Are tab separation valid in data files?

### ISSUE THREAD

**Issue by lucaszanella** [TALP-UPC/FreeLing#47]
I'm working with the go port of freeling which works fine for english, but then I tried to use PT and it gives me an error while separating the following line of tokenizer.dat:

`NAMES_CODES	0  ({ALPHA}|{SYMNUM})*[0-9]({ALPHA}|[0-9]|{SYMNUM}+{ALPHANUM})*`

which turns out to be the only line separated by tab and not space. I could fix that and the code will work but should the code support TAB separation too?

**Comment by lluisp** [comment]
That depends on what you want your port to do.
If it should behave exactly as FreeLing, then the answer is yes. Tabs and spaces are the same for FreeLing.

BTW, note than a port of FreeLing to another programming language is a derived work, and thus must have AGPL license.
