### ISSUE TITLE
No documentation for 'accents'

### ISSUE THREAD

**Issue by lucaszanella** [TALP-UPC/FreeLing#48]
I'm working on a port to the Go language (as requested by you, it'll be released with all the required licenses), and I just realized that the **tokenizer** for the portuguese language will split words at its accents. I see that there is an accents module, so I suppose I should use it to remove accentuation before tokenizing things. Is this the intended usage? Also, even in the examples of how to use the library, there's no accentuation correction before the tokenizer, the tokenizer is the first thing to operate on the raw string.

A simple word in the tokenizer.dat is as the following:

`WORD            0  {ALPHANUM}+[\+]*`

so the intended behavior for the tokenizer is to recognize words without accentuation.

**Comment by lluisp** [comment]
If words are splitted at accents, it is most likely because you are either using a wrong locale or feeding freeling with text that is not encoded in UTF8.

**Comment by lucaszanella** [comment]
I don't get it, the rule for WORD in portuguese tokenizer.dat is just for
alphanumeric characters, it doesn't include accented words

Em 13 de mar de 2017 10:12 AM, "Lluís Padró" <notifications@github.com>
escreveu:

**Comment by lluisp** [comment]
The macro ALPHANUM  is defined as  [[:alnum:]º°]

POSIX regex [[:alnum:]] is locale-sensitive. If you set the right locale (e.g. pt_PT@UTF8, but en_US@UTF8 or es_ES@UTF8 will also work), acented characters are considered alphabetic.

Moreover, I insist:  Input text MUST be UTF8.

**Comment by lucaszanella** [comment]
I understand what you're saying: the string should be utf-8 (which I think it is), but what about locales? Are you saying about the locales of the computer? Mine is english utf-8 and it won't work. I don't understand, if there is a notation for utf-8 regex rules, why they're written in ASCII in tokenizer.dat? I'm having trouble making it work in Go, I even tried it online: https://regex101.com/r/gNKINk/1 and it won't work either. 

I appreciate if you can help me clarify this confusion, because I haven't seen a regex compiler/matcher that will accept the alnum macro for accentuaded words

**Comment by zeehio** [comment]
Hi, I'm just passing by:
According to http://www.regular-expressions.info/posixbrackets.html you may want to replace `[:alnum:]` with `[\p{L}\p{Nl}\p{Nd}]`.

Tested at: http://fiddle.re/gpx78n (click at "go" to test it in go)

**Comment by lluisp** [comment]
@lucaszanella:
 [:alnum:] or [:alpha:]  are codes for "any character that is alphanumeric acording to current locale" or "any character that is alphabetic according to current locale". This is not FreeLing language, is POSIX standard.  In C++ FreeLing, this is handled externaly by boost_locale and boost_regex. 

Regarding system locale, that is not necessarily the one used by the program.  That is why any program calling freeling needs to explicitly set the locale to use with the util::init_locale() function.
If that function is not invoked, freeling will fail to properly identify alphabetic characters.

How to do this in Go, I have no idea.

**Comment by lluisp** [comment]
@zeehio:
  I'm not sure about that...  Then how would you distinguish russian, greek, or arabic characters from latin ?

**Comment by zeehio** [comment]
Oh wow! Relying on POSIX compliance for defining what is considered alphanumeric in any locale and use that in regular expressions! That is cool.

Working at the intersection of regular expressions and locales and on top of that porting to a different programming language must be terrifying...

According to https://golang.org/pkg/regexp/ golang regexp module complies with RE2 specifications, described at https://github.com/google/re2/wiki/Syntax and there `[:alnum:]` is defined as the ASCII version. Getting a Unicode equivalent is easy (that was my suggestion) but getting a locale dependent expression may not be possible... have you thought about defining the regular expression yourselves?

Good luck with this...

**Comment by lluisp** [comment]
I'd would say that what is terrifying is porting FreeLing to Go.

FreeLing is a huge library, with lots of external dependencies, and it is constantly growing. By the time a Go version is finished, it will be already obsolete.

Maybe a better way to use FreeLing from Go would be using SWIG (www.swig.org) to generate an API that can be easily adapted to newer versions... That works pretty good for other languages.

**Comment by lucaszanella** [comment]
I'd like to use this to port, but I have found
https://github.com/advancedlogic/go-freeling which was already large and i
just continued. I also dont know how to port using that library

Em 14 de mar de 2017 1:42 PM, "Lluís Padró" <notifications@github.com>
escreveu:

**Comment by lluisp** [comment]
Well, that is the point... Using SWIG you don't have to port anything.  Just compile an API definition (which is already there) and obtain a Go library that will connect to freeling transparently.

You can have a look at how this is done for other languages in APIs directory in freeling sources.

You may need to fiddle a couple of afternoons with SWIG, but that is much less work than porting everything.
