### ISSUE TITLE
Problem with the path in "Additional Library Directories"

### ISSUE THREAD

**Issue by tmyapple** [TALP-UPC/FreeLing#53]
The path to the dependencies directory is wrong in the projects "libtreeler"/"libfoma"/"libfreeling" under the solution found in msvc/13.0.
instead of "..\..\..\..\dependencies\zlib\lib\x64" it should be "..\..\..\dependencies\zlib\lib\x64"

**Comment by lluisp** [comment]
I think that depends on where you uncompress you "dependencies" folder.
Please check the file msvc/13.0/README  to find out how you need to organize the folders for the solution to work

**Comment by tmyapple** [comment]
i extracted it according to what was written in the README,
according to the path given in the readme (under freeling/deependencies)
the path should be one less ".."


בתאריך 17 במאי 2017 1:01 PM,‏ "Lluís Padró" <notifications@github.com> כתב:

**Comment by lluisp** [comment]
You're right.

 changed, thanks!
