### ISSUE TITLE
error path for include:

### ISSUE THREAD

**Issue by tmyapple** [TALP-UPC/FreeLing#54]
Thre file:  src\libtreeler\treeler\algo\perceptron-v0.1.h has the following include:
#include "treeler/learn/perceptron-v0.1.tcc"
which doesn't exist anymore, i think it should be #include "treeler/algo/perceptron-v0.1.tcc"

**Comment by lluisp** [comment]
You're right. Thanks
However, this template is probably never instantiated in freeling, otherwise this will produce a compilation error.
