### ISSUE TITLE
Lemmatization and WSD

### ISSUE THREAD

**Issue by arademaker** [TALP-UPC/FreeLing#56]
Given https://github.com/TALP-UPC/FreeLing/blob/master/data/pt/afixos.dat#L781-L782  a Portuguese word such as "regularmente" will be lemmatized to "regular" but it would keep the POS RG (adverb) and the WSD module will not find this sense in the Wordnet. This is an interesting problem. I can only think in 3 solutions, both not perfect:

1. lemmatize "regularmente" to "regularmente" (adv = http://wnpt.brlcloud.com/wn/synset?id=00195024-r) and "regular" as "regular" (adj = http://wnpt.brlcloud.com/wn/synset?id=01959294-a). But it will probably almost duplicate the lexicon of adverbs.

2. lemmatize "regularmente" to "regular" and change its POS to ADJ. But it can confuse the parser.

3. lemmatize "regularmente" to "regular" and keep the POS ADV. The current status. It can also confuse the parser and it will require a extra work from the WSD module since it would not make sense to add "regular" in the 00195024-r synset.

**Comment by lluisp** [comment]
I am not sure why this happens, but it looks like an error in the derivational rule for -mente suffix

In Spanish and Catalan  (not sure about Galician) these adverbs keep lemma "regularmente", which is found in WN (if present)

If the word is "regular", then it is an adjective and will be looked up in WN as such, and also found.

So, you can have a look at file "affixes.dat" and locate the rule for "-mente".  Compare it with the rule for "-mente" in spanish and you'll see how they specify a different lemma.

**Comment by merqlove** [comment]
I'm also found trouble with lemmas.

In russian notation it returns sometime:
Form: Великобритании
lemma: великобритании

It's looks ugly, like if we say:
Form: United kingdoms
lemma: united kingdoms

Same rule sometime works for the word Europe in russian, and i mean for many other words.

**Comment by merqlove** [comment]
Tried same with freeling & mystem.
Looks like analyzer stopping when Person or Organization is found.
In this case some it takes right result, sometimes not.

$ echo "Европы" | analyze -f /usr/local/opt/freeling/share/freeling/config/ru.cfg
Европы европы NP 1

$ echo "Путин" | analyze -f /usr/local/opt/freeling/share/freeling/config/ru.cfg
Путин путин NP 0.339848

$ echo "путин" | analyze -f /usr/local/opt/freeling/share/freeling/config/ru.cfg
путин путина NCGPFI0000 1

$ echo "Путин" | mystem
Путин{путин|путина}
$ echo "Европы" | mystem
Европы{европа}
$ echo "жанров" | mystem
жанров{жанр|жанровый}
$ echo "путины" | mystem
путины{путин|путина}
$ echo "обамы" | mystem
обамы{обама}
$ echo "обам" | mystem
обам{обама}
$ echo "Трамп" | mystem
Трамп{трамп}
$ echo "Трампа" | mystem
Трампа{трамп}

**Comment by merqlove** [comment]
ok, i have added mystem as second lemma analyzer, because they is really better in this thing.

**Comment by lluisp** [comment]
I don't read Russian, so I don't understand what is the problem
I guess it is that some lemmas are wrong. There are two possible reasons for that:
1)- The form is in the dictionary with the wrong lemma
2)- The form is not in the dictionary

In case 1), you can just edit the dictionary source (data/ru/dictionary/entries) and fix the error.
In case 2), if the word is not int the dictionary, the guesser will guess the PoS but not the lemma, so it will have the same form as lemma. You can add the word to the dictionary (the same than above) and it will work.

After modyfing or extending the dictionary, you have to run "make install" again to re-generate and install the new dictionary.

Finally, note that morphological analysis in FreeLing relies on a dictionary of all inflected forms. This is not very suitable for highly flexible languages such as Russian, specially if proper nouns are involved, so using an alternative lemmatizer is a good option.

**Comment by merqlove** [comment]
@lluisp Yep, currently  i found `mystem` from Yandex  is more suitable for our needs (as a lemma detector for group of Russian words),  we use this tool after filtering & analysis all `non word` form values via `Freeling`. 

I have to group all final forms via `\n` to get splitted results from `mystem` by single calculation.
 
Freeling works for us as a base data collection maker & positions finder. But it think later it can be realized internally, via Java/Scala stuff.

**Comment by lluisp** [comment]
If you call freeling libray directly from Java, you can find out which words were found in the dictionary (and thus, have a reliable lemma) and which were guessed and need to be run through yandex.

**Comment by merqlove** [comment]
wow, great suggestion, i will try!)))
--
Best regards,
Alexander Merkulov

E-mail: sasha@merqlove.ru
Tel.:  +7(925) 278-44-98
Skype:  merqlove

**Comment by merqlove** [comment]
As i understand, word is not found in thw dict, when its lemma same as form? It is right suggestion? Or i can detect it by tags?

--
Best regards,
Alexander Merkulov

E-mail: sasha@merqlove.ru
Tel.:  +7(925) 278-44-98
Skype:  merqlove

**Comment by merqlove** [comment]
Got it, `Word#foundInDict()`.

--
Best regards,
Alexander Merkulov

E-mail: sasha@merqlove.ru
Tel.:  +7(925) 278-44-98
Skype:  merqlove

**Comment by lluisp** [comment]
Yes, though in latests version this is replaced by word::analyzed_by
