### ISSUE TITLE
Node.js bindings

### ISSUE THREAD

**Issue by sebastianarena** [TALP-UPC/FreeLing#58]
Hello!
I've come across your project, and it seems like a great start for us here to go deep down NLP!
First of all thank you for your awesome support on NLP in Spanish, greatly appreciated.

I wanted to ask about the possibility of adding an API binding for node.js (similar to the one in Python)
I've come across many libraries that use external C++ libraries, and it seems given the fact of all the awesome support for other languages, that node.js would fit right in.

Here's some documentation on the matter: https://nodejs.org/api/addons.html

Love from Argentina

**Comment by lluisp** [comment]
Hi kaminoo
  Our resources are limited, and our main goal is to enhance the linguistic analysis of the library. So, adding new APIs is a low-priority task

  If you want to contribute with a javascript API, it will be very welcome.  Have a look at www.swig.org, that is used to generate all other APIs.  If swig supports javascript, it may be relatively easy to add a new API.

**Comment by kaminoo** [comment]
Hello @lluisp !
Thanks for the quick reply
Completely understood... and thanks for giving us the chance to contribute
I just checked and seems that swig does allow node.js bindings, so I'll test it a do a PR once I feel its right

**Comment by kaminoo** [comment]
So, after a day of trying to make it work... I finally came to a real problem I probably can't solve easily. Swig for Javascript does not declare std::list and std::set.
Granted both of them should not be hard to put on Javascript, there's probably a reason why they are not included by default.
I saw that std::list was included by you guys on Java.
Any tips on how I could make it work?

**Comment by lluisp** [comment]
> Granted both of them should not be hard to put on Javascript, there's probably a reason why they are not included by default.

I'd say that swig heavily relies on contributions for this kind of things.  So, if you create the APIs for those containers, they'll be glad to include them

> I saw that std::list was included by you guys on Java.
> Any tips on how I could make it work?

uhm, that was a long time ago... If I remember well, I copied another class (std_vector I think) and adapted it.  It was no probably the best implementation but it worked
In any case, it will require having a look at how swig handles these conversions (they call them "typemaps" some are already defined, some are not.  Have a look at perl API to see some customized ones), and some understanding on how JS handles its data (so, the Java JNI equivalent in JS).
