### ISSUE TITLE
Portuguese tagset

### ISSUE THREAD

**Issue by arademaker** [TALP-UPC/FreeLing#6]
The file below has conflicts. See the lines with <<< and >>> . These are unsolved conflicts in the file created in a previous merge.

https://github.com/TALP-UPC/FreeLing/blob/master/data/pt/tagset.dat

**Comment by lluisp** [comment]
I fixed it all and pushed it.  You can now get in sync.

A couple of things:

1. I see you added some adverbs ended in -mente.
   These are much better handled with an affixation rule.

2. You also added verb "redemocratizar".
    It would be much better to handle these with a prefix rule for "re+V", so you can analyze any verb like "repintar", "revender", etc.

**Comment by lluisp** [comment]
@arademaker:  What about these affixes I mentioned?

**Comment by arademaker** [comment]
Hi Padro, I opened an issue in our fork at own-pt/FreeLing#1. But we can report the updates here instead. I was expecting @livyreal would contribute but I am working on that now.

```vulgarmente``` is one example of the first case. We can remove ```vulgarmente``` from adv because the rules in the afixos.dat will take care to find ```vulgar``` in the adj file and add the sufix ```mente```.

```
mente    *    ^AQ0CS    RG    0    0    0   L  1 -
mente    *    ^AQ0FS    RG    0    0    0   L  1 -
```

@lluisp , I made some experimental changes removing the redundancies and adding the re- prefix for verbs. How is the best way to debug this changes? I believe that a lot of verbs are now redundant and some adverbs too.  I wounder if we can have a easy way to test for redundances in the entries given the afixos.

**Comment by lluisp** [comment]
There is no fully automatic way to do that, because some words may end in -mente or start in re- but do not need to be removed.
I'd do:
`grep 'mente ' data/pt/dictionary/adv` 
and then manually check the results to see which can be safely removed.

for "re-" prefix, the same:
`grep ' re' data/pt/dictionary/verb | sort | uniq ` 
and manually check which can be deleted

(please notice the whitespaces after "mente" and before "re" in the grep regexps above.)

**Comment by arademaker** [comment]
The afixos rules for ex-, vice- and contra- now split the word in two tokens. It is following the Universal Dependencies approach. See lines 7-9 for one example from the corpus https://github.com/ryanmcd/uni-dep-tb:

```
1       Essa    _       PRON    PRON    _       3       nsubj   _       _
2       também  _       ADV     ADV     _       3       advmod  _       _
3       é       _       VERB    VERB    _       0       ROOT    _       _
4       a       _       DET     DET     _       5       det     _       _
5       avaliação       _       NOUN    NOUN    _       3       attr    _       _
6       do      _       ADP     ADP     _       5       adpmod  _       _
7       ex      _       PRT     PRT     _       9       compmod _       _
8       -       _       .       .       _       9       p       _       _
9       embaixador      _       NOUN    NOUN    _       6       adpobj  _       _
10      do      _       ADP     ADP     _       9       adpmod  _       _
11      Brasil  _       NOUN    PNOUN   _       10      adpobj  _       _
12      nos     _       ADP     ADP     _       9       adpmod  _       _
13      EUA     _       NOUN    PNOUN   _       12      adpobj  _       _
14      Rubens  _       NOUN    PNOUN   _       15      compmod _       _
15      Barbosa _       NOUN    PNOUN   _       9       appos   _       _
16      .       _       .       .       _       3       p       _       _
```

Not sure if this is the best approach... 

The code I used to clean the adv and verbs files is below. This can be improved to make it more general. It would be nice having a procedure to check for redundance in the dict using the afixos.dat file.

```
(ql:quickload :cl-ppcre)

(defun read-data (filename)
  (with-open-file (in filename)
    (let ((dict))
      (do ((line (read-line in nil nil)
		 (read-line in nil nil)))
	  ((null line) (reverse dict))
	(push (cl-ppcre:split "[ ]+" line) dict)))))


(defun clean-suffix (filedata-1 filedata-2 output-file suffix)
  (let ((data1 (read-data filedata-1))
	(data2 (read-data filedata-2))
	(res))
    (dolist (r1 data1 res)
      (if (cl-ppcre:scan (format nil "~a$" suffix) (car r1))
	  (let ((candidate (cl-ppcre:regex-replace suffix (car r1) "")))
	    (format *debug-io* "finding ~a (~a) ~%" (car r1) candidate)
	    (if (not (find candidate data2 :key #'car :test #'equal))
		(push r1 res)))
	  (push r1 res)))
    (with-open-file (out output-file :direction :output :if-exists :supersede)
      (dolist (reg (reverse res))
	(format out "~{~a~^ ~}~%" reg)))))

(clean-suffix "adv" "adjs" "adv-new" "mente")


(defun clean-verbs (filename output)
  (let ((data (read-data filename))
	(res))
    (dolist (r data res)
      (if (cl-ppcre:scan "^re" (car r))
	  (let ((candidate (cl-ppcre:regex-replace "^re" (car r) "")))
	    (format *debug-io* "Finding ~a (~a) ~%" (car r) candidate)
	    (if (not (find-if (lambda (d)
				(and (equal candidate (car d))
				     (equal (caddr r) (caddr d))))
			      data))
		(push r res)))
	  (push r res)))
    (with-open-file (out output :direction :output :if-exists :supersede)
      (dolist (reg (reverse res))
	(format out "~{~a~^ ~}~%" reg)))))

(clean-verbs "verbs" "verbs-new")
```

Some minor changes in the defaults of pt.cfg. The NE module uses bio as default now.

**Comment by lluisp** [comment]
With latest merges, I think we can close this one.
