### ISSUE TITLE
Outdated dependencies.

### ISSUE THREAD

**Issue by merqlove** [TALP-UPC/FreeLing#61]
Package deps like libicu libboost-regex is outdated in some .deb releases (jessie, stretch).

**Comment by merqlove** [comment]
Currently we will use our own builds.
Maybe helpful for anyone.
https://github.com/cnsa/deb-freeling

**Comment by lluisp** [comment]
both libboost and libicu are avaliable as debian official distribution packages.  
https://packages.debian.org/stretch/libs/
https://packages.debian.org/jessie/libs/

The same is true for Ubuntu

You may need to check the exact package name in order to install them appropriately.

**Comment by merqlove** [comment]
Hi, i’m also seen them in of. packages repo.
But required versions does not exists within new Debian container images.

As you can see here https://packages.debian.org/stretch/libs/
 <https://packages.debian.org/stretch/libs/>
boost version is much larger than it’s requirement by Freeling.

So in the new version of these OS boost and so on will be not found by default.

**Comment by lluisp** [comment]
Ah, I guess you mean for binary packages.
You are right, there is no binary package for stretch yet (check "releases" page, supported systems for each package are described there). You should compile FreeLing from source if you want to use it in stretch,
For jessie, there is a tested binary package which should work.

**Comment by merqlove** [comment]
Right, for that needs i did docker auto builder with stretch release. i'm too lazy to compile it in every build :)
