### ISSUE TITLE
DockerFile for the Java API not working

### ISSUE THREAD

**Issue by joancf** [TALP-UPC/FreeLing#66]
I try to install the Docker in APIs/java/Dockerfile but I get some installation errors.
I install it in a Linux Mint 18.1 but the dockerFile is the original file using ubuntu trusty
The  error I get is 
```
Step 8/15 : RUN cd /tmp &&     wget -q --progress=dot:giga https://github.com/TALP-UPC/FreeLing/releases/download/4.0/freeling-4.0-trusty-amd64.deb &&     dpkg -i freeling-4.0-trusty-amd64.deb
 ---> Running in 0a760e5f0bf3
Selecting previously unselected package freeling.
(Reading database ... 32547 files and directories currently installed.)
Preparing to unpack freeling-4.0-trusty-amd64.deb ...
Unpacking freeling (4.0) ...
[91mdpkg: dependency problems prevent configuration of freeling:
 freeling depends on libboost-filesystem1.54.0 (>= 1.54); however:
  Package libboost-filesystem1.54.0 is not installed.

dpkg: error processing package freeling (--install):
 dependency problems - leaving unconfigured
[0m[91mErrors were encountered while processing:
 freeling
[0m
```

So it seems that does not detect correctly  libboost's version (which has version 1.55 installed) as indicated in the apt-get command    
`apt-get install -y automake autoconf libtool wget swig libicu52 libboost-regex1.55.0 libboost-system1.55.0 libboost-program-options1.55.0 `

If I change the version in apt-get to 1.54 then it is able to install freeling...
```
RUN locale-gen en_US.UTF-8 && \
    apt-get install -y automake autoconf libtool wget swig \
                       libicu52 libboost-regex1.54.0 \
                       libboost-system1.54.0 libboost-program-options1.54.0 \
                       libboost-thread1.54.0 libboost-filesystem1.54.0 && \
```

Then the ` dpkg -i freeling-4.0-trusty-amd64.deb`  works with no issues, BUT then 
the make  command fails
here are the first errors...
```
g++ -shared -o /usr/local/lib/libfreeling_javaAPI.so freeling_javaAPI.cxx -lfreeling -L/usr/lib -lboost_system -I/usr/include -I/usr/include/treeler -I/usr/lib/jvm/java-8-oracle/include -I/usr/lib/jvm/java-8-oracle/include/linux -fPIC -std=c++0x
freeling_javaAPI.cxx:508:12: error: 'analyzer' in namespace 'freeling' does not name a type
    typedef freeling::analyzer::config_options config_options;
            ^
freeling_javaAPI.cxx:509:12: error: 'analyzer' in namespace 'freeling' does not name a type
    typedef freeling::analyzer::invoke_options invoke_options;
            ^
freeling_javaAPI.cxx: In function 'jlong Java_edu_upc_freeling_freelingJNI_new_1ListAlternative_1_1SWIG_10(JNIEnv*, jclass)':
freeling_javaAPI.cxx:1045:14: error: 'alternative' is not a member of 'freeling'
   std::list< freeling::alternative > *result = 0 ;
```

I have tried to change the ubuntu version and move it to xenial adapting the version of the parser and the libbboost, but make fails also. 

Any help is welcome!

**Comment by lluisp** [comment]
I am afraid that Dockerfile is third-party provided and it seems it has not been properly checked or updated

It seems .dep package is linked to boost 1.54, so that is why you need to install it.  
Since, it is available in trusty repositories, that solves your first problem, as you managed to do.

The second problem (building the java API) happens because the API source is being obtained from GitHub master, which is now ahead of 4.0 stable release.

Since you installed .deb for 4.0, you need to get the API source from 4.0 (you can wget the tar.gz source file for 4.0 instead of cloning the repo, and that should work from that point on.  
You can follow the docker file you'll find in APIs/docker/Dokerfile in github freeling repository)

The thing is that the API and the library should belong to the same version. The alternative is to install and build everthing from git master (both freeling and the API) instead of intsalling them both from 4.0

**Comment by lluisp** [comment]
I modified the APIs/java/Dockerfile so it uses 4.0 for everything
However it seems it is not setting the enviroment variables required by the Makefile:
```
ENV JAVADIR /usr/lib/jvm/java-8-oracle
ENV SWIGDIR /usr/share/swig2.0
ENV FREELINGDIR /usr
ENV FREELINGOUT /usr/local/lib
```
maybe you are more familiar than me with docker and can sort this out...

**Comment by joancf** [comment]
ok I'll try it. I could also install it from github getting the last version of FreeLing and compiling it in the docker.
Your Dokerfile has an error: you don't need to use "sudo" when removing files because everything is run as root. As sudo is not installed by default then it gives an error. 
The environment variables are set correctly, I add in my solution the classpath. Opening a terminal in the docker and running "env", you can check them, and yes they are there!.
 
Here is my version using Xenial (Because trusty will end its support in the next months)
This version gets the code from git using clone depth 1 (This means that I get the last version, which may not be stable?)  , but there can be other options, as  the one that you propose in the new version: getting the zip file from github, fixing a given tag.

```
FROM ubuntu:xenial
MAINTAINER Joan Codina <joan.codina@upf.edu>

ENV DEBIAN_FRONTEND noninteractive

# repositories and update and upgrade to get the last versions.
RUN apt-get -qq update && \
    apt-get -qq upgrade && \
    apt-get install -qqy software-properties-common curl git build-essential --fix-missing && \
    add-apt-repository -y ppa:webupd8team/java && \
    apt-get -qq update

  
    
# Language setup
RUN apt-get -qqy install language-pack-en-base && \
    update-locale LANG=en_US.UTF-8 && \
    echo "LANGUAGE=en_US.UTF-8" >> /etc/default/locale && \
    echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale && \
    locale-gen en_US.UTF-8

# Freeling Deps
RUN apt-get install -y automake autoconf libtool wget swig build-essential && \
    apt-get install -y libboost-regex-dev libicu-dev zlib1g-dev \
					   libboost-system-dev libboost-program-options-dev libboost-thread-dev
                       

# Install Freeling from github --- take a cofee in the meanwhile
RUN git clone --depth=1 https://github.com/TALP-UPC/FreeLing.git Freeling 
WORKDIR /Freeling
RUN autoreconf --install && ./configure && make && make install

# Java Deps

RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -qq -y oracle-java8-installer
# BUILD JNI
ENV JAVADIR /usr/lib/jvm/java-8-oracle
ENV SWIGDIR /usr/share/swig2.0
ENV FREELINGDIR /usr
ENV FREELINGOUT /usr/local/lib


WORKDIR /Freeling/APIs/java
RUN make all

ENV CLASSPATH=".:/usr/local/lib/"
ENV LD_LIBRARY_PATH=/usr/local/lib/
     
# Cleanup
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /
```

**Comment by lluisp** [comment]
Great, thanks!
Yes, if you get gitHub master, you get the development version which may not be stable, and it is likely to include changes that are not yet reflected in the java API.

I think it is safer to use a stable tag, either cloning or downloading the deb
