### ISSUE TITLE
Candidate Corrections for Mispelled Words not working with Python API

### ISSUE THREAD

**Issue by gbg141** [TALP-UPC/FreeLing#69]
Hi,

I'm trying to use the spell corrector through the Python API, but it seems that the method `get_alternatives()` doesn't retrieve an appropriate object (the SwigPyObject it returns is not iterable, and does not have any method to get the alternative words either). I attach the error I got when executing a piece of code from the example posted on the tutorial webpage:

```
---------------------------------------------------------------------------'
TypeError                                 Traceback (most recent call last)
<ipython-input-23-5909beee38a3> in <module>()
     12     # print alternative forms proposed by the alternative suggestors
     13     print("   ALTERNATIVE FORMS:")
---> 14     for a in w.get_alternatives() :
     15         print(" ["+a.get_form()+","+str(a.get_distance())+"]")
     16     print("")

TypeError: 'SwigPyObject' object is not iterable
```

When calling the method 'has_alternatives()', it properly detects whether there are altrnatives or not; the problem is how to access these data. I'm using Python 2.7 and Freeling 4.0. 

Any idea about what's going on? Thanks in advance.

**Comment by lluisp** [comment]
Mehod get_alternatives has the signature:
 ```
std::list<std::pair<std::wstring,int> >& get_alternatives();
```
But type  `list<pair<wstring,int>`  is not defined in the API generated by swig, and thay is why it ends up mapped to `SwigPyObject`

So, you shoud add it to the file `APIs/common/templates.i`, by adding the line:
```
%template(ListPairStringInt) std::list<std::pair<std::wstring,int> >;
```
(e.g. at the end of the file)
and build the API again

I think that should be enough.

However, you may want to give a try to version 4.1 (there is a branch for it in GitHub) which has a clearer API with a proper `alternative` class, and also provides CMake installation that can build the APIs for you automatically at installation time.
