### ISSUE TITLE
new erros in MacOS

### ISSUE THREAD

**Issue by arademaker** [TALP-UPC/FreeLing#7]
I got from the  HEAD on master branch:

```
$ autoreconf --install
data/Makefile.am:4: error: bad characters in variable name ''
data/Makefile.am:18: error: bad characters in variable name ''
data/Makefile.am:5: warning: variants multiply defined in condition TRUE ...
data/Makefile.am:3: ... 'variants' previously defined here
data/Makefile.am:18: warning:  multiply defined in condition TRUE ...
data/Makefile.am:4: ... '' previously defined here
src/libfreeling/Makefile.am:21: error: bad characters in variable name ''
src/libfreeling/Makefile.am:22: warning: libfreeling_la_SOURCES multiply defined in condition TRUE ...
src/libfreeling/Makefile.am:20: ... 'libfreeling_la_SOURCES' previously defined here
autoreconf: /opt/local/bin/automake failed with exit status: 1
```

**Comment by arademaker** [comment]
and after ```./configure``` and make

```
$ env LDFLAGS="-L/opt/local/lib -L/opt/local/include" CPPFLAGS="-I/opt/local/include -I/opt/local/include/boost" ./configure --enable-boost-locale
...
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `data/Makefile.in'

urca:freeling-my arademaker$ make
Making all in src
make[1]: *** No rule to make target `all'.  Stop.
make: *** [all-recursive] Error 1
```

**Comment by lluisp** [comment]
It seems there are some conflicts that broke a lot of files, and git didn`t warn me about it (or at least, I didn't see...)

 So... back to square one.

**Comment by arademaker** [comment]
yes. I saw it, see my first comment on #6.

**Comment by lluisp** [comment]
I thought it was just that file, but it turns out it is a lot of them...  probaly cause by my lack of experience with git(hub).
I will rollback to the latest point were things were consistent, and we'll probably need to apply again some changes about pt data.

**Comment by lluisp** [comment]
Ok, I rolled back to the point where things were working, and then added again your update on pt data.
So, now everything should be ok, 

__BUT:__  Your fork is now incorrect, since it contains all the unfixed conflicts.
  Please remove it and fork again (or make sure you sync with current master, pullng everything and discarding any local conflicts you may have)

**Comment by arademaker** [comment]
now working . Some issue on mac os with encoding 

```
$ echo 'testando situação agora.' | analyze -f pt.cfg
testando testar VMG0000 1
situa� situa� RG 0.365785
� � Fz 1
� � NP00000 1
� � Fz 1
o o DA0MS0 0.950254
agora agora RG 1
. . Fp 1
```

and two entries in the dict, I will submit a pull request. Any idea about the encoding problem?

**Comment by arademaker** [comment]
unfortunately, we lost the contribution history in the commits, but this is ok.

**Comment by lluisp** [comment]
It seems ok for me
```
$ file  data/pt/dictionary/entries/nouns 
data/pt/dictionary/entries/nouns: UTF-8 Unicode text
```
```
$ grep ^situa data/pt/dictionary/entries/nouns 
(...)
situacionistas situacionista NCCP000
situações situação NCFP000
situação situação NCFS000
```

Maybe it is your locale settings?

**Comment by arademaker** [comment]
closing this issue for open a more specific one about locales problem in MacOS.
