### ISSUE TITLE
4.1 segfault

### ISSUE THREAD

**Issue by ilovezfs** [TALP-UPC/FreeLing#71]
https://gist.github.com/ilovezfs/389539ede39e49df122089af9d0a883d

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libfreeling.dylib             	0x000000010e601788 freeling::database::dump_database(std::__1::basic_ostream<wchar_t, std::__1::char_traits<wchar_t> >&, bool) const + 26
1   libfreeling.dylib             	0x000000010e6678bc freeling::compounds::compounds(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, freeling::dictionary const&) + 3068
2   libfreeling.dylib             	0x000000010e5f37bc freeling::dictionary::dictionary(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, bool, bool) + 1692
3   libfreeling.dylib             	0x000000010e5f47a4 freeling::dictionary::dictionary(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, bool, bool) + 24
4   libfreeling.dylib             	0x000000010e664c10 freeling::maco::maco(freeling::maco_options const&) + 404
5   libfreeling.dylib             	0x000000010e5ea452 freeling::analyzer::analyzer(freeling::analyzer::analyzer_config_options const&) + 792
6   analyzer                      	0x000000010e5912d0 main + 169
7   libdyld.dylib                 	0x00007fff9acda5ad start + 1
```
running
```
  test do
    expected = <<~EOS
      Hello hello NN 1
      world world NN 1
    EOS
    assert_equal expected, pipe_output("#{bin}/analyze -f #{pkgshare}/config/en.cfg", "Hello world").chomp
  end
```

**Comment by lluisp** [comment]
Does it crash at load time?  or when processing?
Please run the script /usr/local/Cellar/freeling/4.1/bin/analyze  (no final "r") in the command line without piping any input: 
  /usr/local/Cellar/freeling/4.1/bin/analyze -f en.cfg
 wait one minute or so to make sure load was successful.
If it doesn't crash at load, type "hello word" , enter, and ctl-D 

Please let me know in which moment it crashes
Which OSX version are you using?

**Comment by lluisp** [comment]
I added #1 to CMakeLists.txt (in master branch)
#2 is less clear... FreeLing is a library and expects to be called with proper parameters. In any case, the calling program could capture exceptions if needed.
Maybe "analyzer" should do the checking and exception handling, but it is mainly an extended example, and the code would get less readable with all that...  I'll think about it.

  thanks!

**Comment by lluisp** [comment]
I see you are building a brew formula for FreeLing.
Is it stable? Is it ok if I add this as the prefered way to install FreeLing on Mac?
thanks

**Comment by ilovezfs** [comment]
>I see you are building a brew formula for FreeLing.
>Is it stable? Is it ok if I add this as the prefered way to install FreeLing on Mac?
>thanks


Yes, it should be stable. We haven't received any complaints or bug reports about the formula.
