### ISSUE TITLE
4.1 checksum mismatch

### ISSUE THREAD

**Issue by ilovezfs** [TALP-UPC/FreeLing#72]
On 17 April the SHA-256 checksum for https://github.com/TALP-UPC/FreeLing/releases/download/4.1/FreeLing-4.1.tar.gz was 12c93aa1ce33b69c5ff4a2dadd8425d12db015c544f27333c4983ce7fdfc8b32

Today it's ccb3322db6851075c9419bb5e472aa6b2e32cc7e9fa01981cff49ea3b212247e.

**Comment by lluisp** [comment]
Yes, there was a small bug and I updated the package and re-tagged the version. 
You were the only one to have downloaded it... sorry for the inconvenience.

**Comment by ilovezfs** [comment]
OK. Thanks for confirming!
