### ISSUE TITLE
Unexpected closing of section </Entries> in file /usr/local/share/freeling/en/dicc.src

### ISSUE THREAD

**Issue by maferblancor** [TALP-UPC/FreeLing#73]
Hi, im trying to run the example given in [https://talp-upc.gitbooks.io/freeling-tutorial/content/code/example01.cc.html](Example) and I'm getting this message, you know why? 
![Uploading capture.png…](Capture)

**Comment by maferblancor** [comment]
The examples I'm using are in `https://github.com/maferblancor/TranslatorES-LSV/tree/master/my_samples` I compile the API for python and I'm getting the same error. I think this may be a problem with the files. I just clone the repository and run the steps in INSTALL.linux  @lluisp Any help??

**Comment by lluisp** [comment]
It may be that the dictionaries are not properly created.
Check the content of /usr/local/share/freeling/en/dicc.src
If it is empty, then there was some error during "make install".

**Comment by maferblancor** [comment]
Well in fact i have tried why several languages and i have review all the dicc files and they all seem to be ok. 
`<IndexType>
DB_MAP
</IndexType>
<Entries>
& & CC
' ' POS
'cause because IN
'd have VBD would MD
'em them PRP
'n' and CC
's 's POS be VBZ have VBZ
'til until IN
'tween between RB
a a DT a NN
a.k.a a.k.a JJ
a.k.a. a.k.a. JJ
aardvark aardvark NN
aardvarks aardvark NNS
abacavir abacavir NN
abaci abacus NNS
aback aback RB
abacus abacus NN
abacuses abacus NNS
abalone abalone NN
abalones abalone NNS
abandon abandon VB abandon VBP
abandoned abandon VBD abandon VBN
abandoning abandon VBG
abandonment abandonment NN
abandons abandon VBZ
abase abase VB abase VBP
abased abase VBD abase VBN
abases abase VBZ
abash abash VB abash VBP
abashed abash VBD abash VBN
abashes abash VBZ
abashing abash VBG
abasing abase VBG
abate abate VB abate VBP
abated abate VBD abate VBN
abatement abatement NN
abatements abatement NNS
abates abate VBZ
abating abate VBG
abattoir abattoir NN
abattoirs abattoir NNS
abbey abbey NN
abbeys abbey NNS
abbot abbot NN
abbots abbot NNS
abbreviate abbreviate VB abbreviate VBP
abbreviated abbreviate VBD abbreviate VBN
abbreviates abbreviate VBZ
abbreviating abbreviate VBG
abbreviation abbreviation NN
abbreviations abbreviation NNS
abcess abcess NN
abcesses abcess NNS
abdicate abdicate VB abdicate VBP
abdicated abdicate VBD abdicate VBN
abdicates abdicate VBZ
abdicating abdicate VBG
abdication abdication NN
abdications abdication NNS
abdomen abdomen NN
abdomens abdomen NNS
abdomina abdomen NNS
abdominal abdominal JJ abdominal NN`

**Comment by lluisp** [comment]
did you try with the default "analyze" command?
``analyze -f en.cfg < mytext.txt``
if that works, then freeling is properly installed, and the problem is in your program.

**Comment by maferblancor** [comment]
No, i tried and i get this message: 

> bash: /usr/local/bin/analyze: /bin/bash^M: intérprete erróneo: No existe el archivo o el directorio

So i have a problem with the installation of Freeling, I guess...So, what do you recommend me to do?

**Comment by lluisp** [comment]
Did you run "make install"?  did you get any errors? 
You can try installing from scratch. Check the instructions in the [user manual](https://talp-upc.gitbooks.io/freeling-4-1-user-manual/content/installation.html), they might be more detailed than the README.
