### ISSUE TITLE
Freeling outputs wrong dependency trees from command line

### ISSUE THREAD

**Issue by ajason08** [TALP-UPC/FreeLing#74]
I'm using windows7 64bits and the [Freeling-4.0-win64 binary version](https://github.com/TALP-UPC/FreeLing/releases/download/4.0/freeling-4.0-win64.zip).

I realized when I compared the output with the result in the [demo online](http://nlp.lsi.upc.edu/freeling/demo/demo.php)

I think this occurs in many cases and maybe occurs in other languages (I just tried english and spanish) but for example, consider this sentence

> Maintenance of Th1 responses and dendritic cell (DC ) functions are compromised in HIV-1 infected individuals.

My expected result is that given by the demo_online
![image](https://user-images.githubusercontent.com/8420899/39377940-83ba9ec8-4a1c-11e8-9e1d-46dc33165f70.png)

but despite I tried different output formats (freeling, xml, json, naf) I got the same dependency tree, which I consider wrong, and it is actually different to that given by the demo. Maybe I'm doing some wrong, this is the command I used `>analyzer.bat -f en.cfg --output xml --outlv dep <ana.txt`

So, the xml shown in the demo_online is actually different from the xml output via command line. I attach this file and some pictures I did in order to facilitate comparisons between both results (green annotation means "sub-tree when both outputs are agree").

![from demo](https://user-images.githubusercontent.com/8420899/39379264-564e7640-4a20-11e8-9a32-dbcbca52e921.png)
![from command line](https://user-images.githubusercontent.com/8420899/39379265-566211dc-4a20-11e8-95b9-72a7a17c29ea.png)
[freeling_output_via_commandline.txt](https://github.com/TALP-UPC/FreeLing/files/1956239/freeling_output_via_commandline.txt)

Finally, if you consider necessary, I could get some statistics to show how many times this occurs.

I appreciate your help with this issue.

**Comment by lluisp** [comment]
The demo runs FreeLing 4.1, so the output may be slightly different from that you get from version 4.0

In any case, keep in mind that state of the art of dependency parsers is about 90%-92%. Either FreeLing or any other parser you can get will output some wrong trees sometimes. There is nothing you can do about that, except wait for science to leap forward.

**Comment by Alezas** [comment]
en linea de comandos que instruccion es necesaria para obtener el arbol de dependencias con freeling?

**Comment by lluisp** [comment]
That is option "OutputLevel" (in the config file) or  "--outlv" (command line)

You'll find valid values for this option (and any other) in the user manual:
https://freeling-user-manual.readthedocs.io/en/v4.2/toc/

Also, running "analyzer --help" will list available options and possible values

**Comment by Alezas** [comment]
thanks for your answer, but in freeling is possible extract collocations?

**Comment by lluisp** [comment]
FreeLing analyzes text and provides you with linguistic information about it (lemmas, categories, syntactic funcitions, trees, etc.)

FreeLing is an utility library devised to ease the building of higher-level NLP applications, not an end-user application for statistical corpus analysis.
What the analysis produced by FL are used for (counting statistics such as collocations, performing translation, text classification, or whatever) is left for the application using FreeLing. It is not possible for FL to cover all imaginable uses of the results of the text analysis.
