### ISSUE TITLE
Python API not working

### ISSUE THREAD

**Issue by vijaynatesan** [TALP-UPC/FreeLing#76]
Environment - Mac OS High Sierra
Freeling installation - Homebrew v 4.1
Issue - Python API not working
Issue Detail - I have successfully executed make on python 2.7 with no error. But when I tried to execute python sample.py, I am getting following error

Traceback (most recent call last):
  File "sample.py", line 10, in <module>
    import pyfreeling
  File "/Users/lab/code/FreeLing-4.1/APIs/python2/pyfreeling.py", line 17, in <module>
    _pyfreeling = swig_import_helper()
  File "/Users/lab/code/FreeLing-4.1/APIs/python2/pyfreeling.py", line 16, in swig_import_helper
    return importlib.import_module('_pyfreeling')
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _pyfreeling

**Below is the Makefile**
# You may need to change these paths to match your installation.
# Alternatively, you can call 'make' overriding variable values, E.g.:
#     make FREELINGDIR=/my/freeling/dir PYTHONDIR=/my/python/dir

FREELINGDIR = /usr/local/Cellar/freeling/4.1
PYTHONVER = python2.7
PYTHONDIR = /usr/include/python2.7

_freeling.so: freeling_pythonAPI.cxx
#       g++ -shared -o _freeling.so freeling_pythonAPI.cxx -lfreeling -I$(FREELINGDIR)/include -L$(FREELINGDIR)/lib -I$(PYTHONDIR) -fPIC -std=gnu++0x
#       Mac OSX users:  Comment the line above, and uncomment the line below:
        g++ -dynamiclib -o _freeling.so freeling_pythonAPI.cxx -lboost_system -l$(PYTHONVER) -lfreeling -I$(FREELINGDIR)/include -L$(FREELINGDIR)/lib -I$(PYTHONDIR) $(CPPFLAGS) $(LDFLAGS) -fPIC  -std=c++0x

freeling_pythonAPI.cxx: freeling_pythonAPI.i ../common/freeling.i ../common/templates.i
        swig -python -c++ -o freeling_pythonAPI.cxx freeling_pythonAPI.i
#       Python2 users: Remove option "-py3" from the above line

clean:
        rm -rf __pycache__ freeling_pythonAPI.cxx _freeling.so freeling.py*

**Comment by lluisp** [comment]
In version 4.1, python APIS can built when you compile FreeLing.
Just add option -DPYTHON2_API=ON to your cmake command.

Using the Makefile is also possible, but it has not been adapted to 4.1 (actually it shouldn't be there).
The makefile creates a library named _freeling.so.  You should rename it to _pyfreeling.so.

**Comment by vijaynatesan** [comment]
Thank you so much for the quick response. Your suggestion worked -  renaming _freeling.so to _pyfreeling.so solved the issue. 

Just FYI - This works only for python3. The python2 throws below error on import pyfreeling
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

Closing the issue.

**Comment by lluisp** [comment]
On 17/05/18 18:14, vijaynatesan wrote:
>
> Thank you so much for the quick response. Your suggestion worked - 
> renaming _freeling.so to _pyfreeling.so solved the issue.
>
> Just FYI - This works only for python3. The python2 throws below error 
> on import pyfreeling
> Fatal Python error: PyThreadState_Get: no current thread
>    Abort trap: 6
>

  APIs for python2 and 3 are different.  You need to generate them 
separately (so, you'll have a _pyfreeling.so for each of them)

-- 
---------------------------------------------------
  Lluís Padró
  Computer Science Departament
  TALP Research Center
  UNIVERSITAT POLITÈCNICA DE CATALUNYA
  http://www.cs.upc.edu/~padro
---------------------------------------------------
