### ISSUE TITLE
Error to build Freeling Java API under WINDOWS

### ISSUE THREAD

**Issue by solartes** [TALP-UPC/FreeLing#80]
When does it generate? : Running swig with freeling_javaAPI.i 
In order to: Build freeling Java API
Error: "freeling_javaAPI.i(47) : Error: Syntax error in input(1)."

Following this tutorial: https://github.com/TALP-UPC/FreeLing/blob/master/APIs/java/README.Win.md

**Comment by lluisp** [comment]
Version 4.1 includes cmake scripts that generate java APIs automatically.
check: https://talp-upc.gitbooks.io/freeling-4-1-user-manual/content/installation/installation-source.html
and: https://talp-upc.gitbooks.io/freeling-4-1-user-manual/content/installation/apis-windows.html
