### ISSUE TITLE
Running analyzer with module "Alternative Suggestion"

### ISSUE THREAD

**Issue by Sedaj** [TALP-UPC/FreeLing#85]
Hi,

I am playing around with analyzer.bat and im trying to run it with support of module Alternative Suggestion ( https://talp-upc.gitbook.io/freeling-4-0-user-manual/processing-classes/alternatives ) for mispelled words. 

I am running it in server mode with default config file but I cannot seem to find any option to enable this module in https://talp-upc.gitbook.io/freeling-4-0-user-manual/analyzer#configuration-file-and-command-line-options .

Any help will be greatly appreciated

**Comment by lluisp** [comment]
the "analyzer.bat" program is a demo of *some* of the FreeLing capabilities, and "alternatives" is not one of them.
Keep in mind that FreeLing is a library (or a toolbox if you prefer), so it can be used in thousands of differents ways, and it is not possible to demonstrate all of them in a single program.

However, in the source code, you'll find a directory src/main/simple_examples where some of this functionalities are shown (including "alternatives").
That example is also in the tutorial (follow link "documentation" -> "tutorial" in FL webpage).

**Comment by Sedaj** [comment]
Hi, 
I was actually able to edit the source code of analyzer and I've added the module to reflect my use-case and compiled it successfully. Thank you for great work !
